spring.application.name=metrics-service


spring.datasource.url=jdbc:postgresql://postgres-db:5432/metrics_db
spring.datasource.username=metrics_user
spring.datasource.password=metrics_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=redis-cache
spring.data.redis.port=6379


spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate


app.rate-limit.global.capacity=1000
app.rate-limit.global.duration=1s
app.rate-limit.client.capacity=10
app.rate-limit.client.duration=1s
app.rate-limit.redis-ttl=5m
app.jwt.secret=g6D6l7VYzgcHgpu/fb/wW0MFMOOpQLFgblbhzP5N9rg=
app.jwt.expiration-hours=1
spring.security.user.name=none
spring.security.user.password=none
